# Generated by Django 5.2.2 on 2025-06-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100, null=True)),
                ('emp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Client_app.employee')),
            ],
        ),
    ]
