# Generated by Django 5.2.2 on 2025-06-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0005_employee_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100, null=True)),
                ('pub', models.ManyToManyField(null=True, related_name='books', to='Client_app.employee')),
            ],
        ),
    ]
