# Generated by Django 5.2.2 on 2025-06-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0007_rename_name_publisher_pubname_admin_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
