# Generated by Django 5.2.2 on 2025-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0008_admin_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
